from enum import Enum
from sheet_project.engine.classes.abilities import ABILITIES


class ARMORPROF(Enum):
    LIGHT = "light"
    MEDIUM = "medium"
    HEAVY = "heavy"
    SHIELD = "shield"

class WEPPROF(Enum):
    MARTIAL = "martial"
    SIMPLE = "simple"

class SKILLPROF(Enum):
    ATHLETICS = "athletics"
    ACROBATICS = "acrobatics"
    SLEIGHT_OF_HAND = "sleight_of_hand"
    STEALTH = "stealth"
    ARCANA = "arcana"
    HISTORY = "history"
    INVESTIGATION = "investigation"
    NATURE = "nature"
    RELIGION = "religion"
    ANIMAL_HANDLING = "animal_handling"
    INSIGHT = "insight"
    MEDICINE = "medicine"
    PERCEPTION = "perception"
    SURVIVAL = "survival"
    DECEPTION = "deception"
    INTIMIDATION = "intimidation"
    PERFORMANCE = "performance"
    PERSUASION = "persuasion"

SKILL_TO_ABILITY = {
    SKILLPROF.ATHLETICS: ABILITIES.STRENGTH,
    SKILLPROF.ACROBATICS: ABILITIES.DEXTERITY,
    SKILLPROF.SLEIGHT_OF_HAND: ABILITIES.DEXTERITY,
    SKILLPROF.STEALTH: ABILITIES.DEXTERITY,
    SKILLPROF.ARCANA: ABILITIES.INTELLIGENCE,
    SKILLPROF.HISTORY: ABILITIES.INTELLIGENCE,
    SKILLPROF.INVESTIGATION: ABILITIES.INTELLIGENCE,
    SKILLPROF.NATURE: ABILITIES.INTELLIGENCE,
    SKILLPROF.RELIGION: ABILITIES.INTELLIGENCE,
    SKILLPROF.ANIMAL_HANDLING: ABILITIES.WISDOM,
    SKILLPROF.INSIGHT: ABILITIES.WISDOM,
    SKILLPROF.MEDICINE: ABILITIES.WISDOM,
    SKILLPROF.PERCEPTION: ABILITIES.WISDOM,
    SKILLPROF.SURVIVAL: ABILITIES.WISDOM,
    SKILLPROF.DECEPTION: ABILITIES.CHARISMA,
    SKILLPROF.INTIMIDATION: ABILITIES.CHARISMA,
    SKILLPROF.PERFORMANCE: ABILITIES.CHARISMA,
    SKILLPROF.PERSUASION: ABILITIES.CHARISMA,
}