from enum import Enum

class SKILLPROFICIENCY(Enum):
    ATHLETICS: 1
    ACROBATICS: 2
    SLEIGHT_OF_HAND: 3
    STEALTH: 4
    ARCANA: 5
    HISTORY: 6
    INVESTIGATION: 7
    NATURE: 8
    RELIGION: 9
    ANIMAL_HANDLING: 10
    INSIGHT: 11
    MEDICINE: 12
    PERCEPTION: 13
    SURVIVAL: 14
    DECEPTION: 15
    INTIMIDATION: 16
    PERFORMANCE: 17
    PERSUASION: 18

class ARMORTRAINING(Enum):
    LIGHT: 1
    MEDIUM: 2
    HEAVY: 3
    SHIELDS: 4

class WEAPONTRAINING(Enum):
    SIMPLE: 1
    MARTIAL: 2